on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: david-marconis/trivy-action@248e3f1ae9550400733c4410e0fdc2e264a19b5b
        with:
          image-ref: node:23.2.0-alpine3.20
          severity: CRITICAL,HIGH
          exit-code: 0
          output: test.txt

      - uses: david-marconis/trivy-action@248e3f1ae9550400733c4410e0fdc2e264a19b5b
        env:
          TRIVY_FORMAT: table
          TRIVY_OUTPUT: ""
        with:
          image-ref: node:22
          severity: CRITICAL,HIGH
          exit-code: 1
          format: sarif
