on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: david-marconis/trivy-action@9bd8b9689e7ae07ab1e8752e555ddf32cdfb28d0
        with:
          image-ref: node:23.2.0-alpine3.20
          severity: CRITICAL,HIGH
          exit-code: 0
          format: sarif
      - uses: david-marconis/trivy-action@9bd8b9689e7ae07ab1e8752e555ddf32cdfb28d0
        with:
          image-ref: node:23.2.0-alpine3.20
          severity: CRITICAL,HIGH
          exit-code: 1
          format: table
