on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: node:23.2.0-alpine3.20
          severity: CRITICAL,HIGH
          exit-code: 0
          format: sarif
      - uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: node:23.2.0-alpine3.20
          severity: CRITICAL,HIGH
          exit-code: 1
          format: table
